### ISSUE TITLE
Increase language support for French.

### ISSUE THREAD

**Issue by mookman288** [mookman288/crisis.js#10]
crisis.js needs to be expanded beyond `src/langs/en.js`. The `src/templates/template.jst` file can be used for contribution. The `development` branch can be used as a starting point. 
- The `gulpfile.js` will need to be updated for the language ('fr')
- A new `fr.js` in `src/langs` will need to be created matching the spirit of the application to the language.
- A new `index.fr.html` will need to be created that explains the application and shows it off with examples.
- A new `README.FR.MD` will need to be created. 
- Please use global neutral resources for now. 

Please make your PRs to the development branch.

**Comment by chatpion** [comment]
It is said in the README that an index-xx.html is needed. Which format do you need then : index.xx.html or index-xx.html ?

**Comment by mookman288** [comment]
Good catch. Go with dashes, since that's what I had originally planned on.
